"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ArchiveClientDocumentRequestTypedDict(TypedDict):
    client_document_id: int


class ArchiveClientDocumentRequest(BaseModel):
    client_document_id: Annotated[
        int,
        pydantic.Field(alias="clientDocumentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class ArchiveClientDocumentValueTypedDict(TypedDict):
    r"""Value"""


class ArchiveClientDocumentValue(BaseModel):
    r"""Value"""


class ArchiveClientDocumentFieldsTypedDict(TypedDict):
    r"""Updated Fields"""

    name: NotRequired[str]
    r"""Name"""
    value: NotRequired[ArchiveClientDocumentValueTypedDict]
    r"""Value"""
    value_update_time: NotRequired[float]
    r"""Value Last Updated"""


class ArchiveClientDocumentFields(BaseModel):
    r"""Updated Fields"""

    name: Optional[str] = None
    r"""Name"""

    value: Optional[ArchiveClientDocumentValue] = None
    r"""Value"""

    value_update_time: Optional[float] = None
    r"""Value Last Updated"""


class ArchiveClientDocumentResponseBodyTypedDict(TypedDict):
    r"""Returns the organization document archived"""

    document_id: NotRequired[int]
    r"""Document Identifier"""
    document_name: NotRequired[str]
    r"""Document Name"""
    document_description: NotRequired[str]
    r"""Document Description"""
    document_update_time: NotRequired[float]
    r"""Document Last Updated"""
    fields: NotRequired[List[ArchiveClientDocumentFieldsTypedDict]]
    r"""Fields"""
    document_template_id: NotRequired[int]
    r"""Document Template Identifier"""
    document_template_name: NotRequired[str]
    r"""Document Template Name"""
    organization_id: NotRequired[int]
    r"""Organization Identifier"""


class ArchiveClientDocumentResponseBody(BaseModel):
    r"""Returns the organization document archived"""

    document_id: Optional[int] = None
    r"""Document Identifier"""

    document_name: Optional[str] = None
    r"""Document Name"""

    document_description: Optional[str] = None
    r"""Document Description"""

    document_update_time: Optional[float] = None
    r"""Document Last Updated"""

    fields: Optional[List[ArchiveClientDocumentFields]] = None
    r"""Fields"""

    document_template_id: Optional[int] = None
    r"""Document Template Identifier"""

    document_template_name: Optional[str] = None
    r"""Document Template Name"""

    organization_id: Optional[int] = None
    r"""Organization Identifier"""
