"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
import io
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateRelatedItemForEntity1PathParamEntityType(str, Enum):
    ORGANIZATION = "ORGANIZATION"
    DOCUMENT = "DOCUMENT"
    LOCATION = "LOCATION"
    NODE = "NODE"
    CHECKLIST = "CHECKLIST"
    KB_DOCUMENT = "KB_DOCUMENT"


class CreateRelatedItemForEntity1RequestTypedDict(TypedDict):
    entity_type: CreateRelatedItemForEntity1PathParamEntityType
    entity_id: int
    request_body: NotRequired[Union[bytes, IO[bytes], io.BufferedReader]]


class CreateRelatedItemForEntity1Request(BaseModel):
    entity_type: Annotated[
        CreateRelatedItemForEntity1PathParamEntityType,
        pydantic.Field(alias="entityType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    entity_id: Annotated[
        int,
        pydantic.Field(alias="entityId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    request_body: Annotated[
        Optional[Union[bytes, IO[bytes], io.BufferedReader]],
        FieldMetadata(request=RequestMetadata(media_type="*/*")),
    ] = None


class CreateRelatedItemForEntity1Type(str, Enum):
    r"""Type of Relation"""

    VALUE = "VALUE"
    ENTITY = "ENTITY"


class CreateRelatedItemForEntity1EntityTypedDict(TypedDict):
    r"""Entity"""


class CreateRelatedItemForEntity1Entity(BaseModel):
    r"""Entity"""


class CreateRelatedItemForEntity1EntityType(str, Enum):
    r"""Entity Type"""

    ORGANIZATION = "ORGANIZATION"
    DOCUMENT = "DOCUMENT"
    LOCATION = "LOCATION"
    NODE = "NODE"
    CHECKLIST = "CHECKLIST"
    KB_DOCUMENT = "KB_DOCUMENT"


class CreateRelatedItemForEntity1RelEntityTypedDict(TypedDict):
    r"""Related Entity"""


class CreateRelatedItemForEntity1RelEntity(BaseModel):
    r"""Related Entity"""


class CreateRelatedItemForEntity1RelatedItemsRelEntityType(str, Enum):
    r"""Related Entity Type"""

    ORGANIZATION = "ORGANIZATION"
    DOCUMENT = "DOCUMENT"
    LOCATION = "LOCATION"
    NODE = "NODE"
    ATTACHMENT = "ATTACHMENT"
    TECHNICIAN = "TECHNICIAN"
    CREDENTIAL = "CREDENTIAL"
    CHECKLIST = "CHECKLIST"
    END_USER = "END_USER"
    CONTACT = "CONTACT"
    KB_DOCUMENT = "KB_DOCUMENT"
    SECURE = "SECURE"


class CreateRelatedItemForEntity1ValueTypedDict(TypedDict):
    r"""Related item value (Attachment meta data / Secure information)"""


class CreateRelatedItemForEntity1Value(BaseModel):
    r"""Related item value (Attachment meta data / Secure information)"""


class CreateRelatedItemForEntity1ResponseBodyTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Identifier"""
    type: NotRequired[CreateRelatedItemForEntity1Type]
    r"""Type of Relation"""
    entity: NotRequired[CreateRelatedItemForEntity1EntityTypedDict]
    r"""Entity"""
    entity_id: NotRequired[int]
    r"""Entity Identifier"""
    entity_type: NotRequired[CreateRelatedItemForEntity1EntityType]
    r"""Entity Type"""
    rel_entity: NotRequired[CreateRelatedItemForEntity1RelEntityTypedDict]
    r"""Related Entity"""
    rel_entity_id: NotRequired[int]
    r"""Related Entity Identifier"""
    rel_entity_type: NotRequired[CreateRelatedItemForEntity1RelatedItemsRelEntityType]
    r"""Related Entity Type"""
    value: NotRequired[CreateRelatedItemForEntity1ValueTypedDict]
    r"""Related item value (Attachment meta data / Secure information)"""
    create_time: NotRequired[float]
    r"""Creation time"""
    update_time: NotRequired[float]
    r"""Last update time"""
    created_by_app_user_id: NotRequired[int]
    r"""The identifier of the user who created the related item"""
    updated_by_app_user_id: NotRequired[int]
    r"""The identifier of the last user to update the related item"""


class CreateRelatedItemForEntity1ResponseBody(BaseModel):
    id: Optional[int] = None
    r"""Identifier"""

    type: Optional[CreateRelatedItemForEntity1Type] = None
    r"""Type of Relation"""

    entity: Optional[CreateRelatedItemForEntity1Entity] = None
    r"""Entity"""

    entity_id: Annotated[Optional[int], pydantic.Field(alias="entityId")] = None
    r"""Entity Identifier"""

    entity_type: Annotated[
        Optional[CreateRelatedItemForEntity1EntityType],
        pydantic.Field(alias="entityType"),
    ] = None
    r"""Entity Type"""

    rel_entity: Annotated[
        Optional[CreateRelatedItemForEntity1RelEntity],
        pydantic.Field(alias="relEntity"),
    ] = None
    r"""Related Entity"""

    rel_entity_id: Annotated[Optional[int], pydantic.Field(alias="relEntityId")] = None
    r"""Related Entity Identifier"""

    rel_entity_type: Annotated[
        Optional[CreateRelatedItemForEntity1RelatedItemsRelEntityType],
        pydantic.Field(alias="relEntityType"),
    ] = None
    r"""Related Entity Type"""

    value: Optional[CreateRelatedItemForEntity1Value] = None
    r"""Related item value (Attachment meta data / Secure information)"""

    create_time: Annotated[Optional[float], pydantic.Field(alias="createTime")] = None
    r"""Creation time"""

    update_time: Annotated[Optional[float], pydantic.Field(alias="updateTime")] = None
    r"""Last update time"""

    created_by_app_user_id: Annotated[
        Optional[int], pydantic.Field(alias="createdByAppUserId")
    ] = None
    r"""The identifier of the user who created the related item"""

    updated_by_app_user_id: Annotated[
        Optional[int], pydantic.Field(alias="updatedByAppUserId")
    ] = None
    r"""The identifier of the last user to update the related item"""
