"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DownloadRelatedItemAttachmentRequestTypedDict(TypedDict):
    related_item_id: int


class DownloadRelatedItemAttachmentRequest(BaseModel):
    related_item_id: Annotated[
        int,
        pydantic.Field(alias="relatedItemId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
