"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCustomFieldsPolicyConditionRequestTypedDict(TypedDict):
    policy_id: int
    condition_id: str


class GetCustomFieldsPolicyConditionRequest(BaseModel):
    policy_id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    condition_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]


class GetCustomFieldsPolicyConditionSeverity(str, Enum):
    r"""Policy condition severity"""

    NONE = "NONE"
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"


class GetCustomFieldsPolicyConditionPriority(str, Enum):
    r"""Policy condition priority"""

    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class GetCustomFieldsPolicyConditionRunAs(str, Enum):
    r"""Policy condition script runAs"""

    SYSTEM = "SYSTEM"
    LOGGED_ON_USER = "LOGGED_ON_USER"
    LOCAL_ADMIN = "LOCAL_ADMIN"
    DOMAIN_ADMIN = "DOMAIN_ADMIN"
    PREFERRED_CREDENTIAL_MAC = "PREFERRED_CREDENTIAL_MAC"
    PREFERRED_CREDENTIAL_LINUX = "PREFERRED_CREDENTIAL_LINUX"


class GetCustomFieldsPolicyConditionScriptVariablesTypedDict(TypedDict):
    r"""Policy condition script variable"""

    id: NotRequired[str]
    r"""Policy condition script variable Id"""
    value: NotRequired[str]
    r"""Policy condition script variable value"""


class GetCustomFieldsPolicyConditionScriptVariables(BaseModel):
    r"""Policy condition script variable"""

    id: Optional[str] = None
    r"""Policy condition script variable Id"""

    value: Optional[str] = None
    r"""Policy condition script variable value"""


class GetCustomFieldsPolicyConditionScriptsTypedDict(TypedDict):
    r"""Policy condition script"""

    script_id: NotRequired[int]
    r"""Policy condition script id"""
    run_as: NotRequired[GetCustomFieldsPolicyConditionRunAs]
    r"""Policy condition script runAs"""
    script_param: NotRequired[str]
    r"""Policy condition script parameter"""
    script_variables: NotRequired[
        List[GetCustomFieldsPolicyConditionScriptVariablesTypedDict]
    ]
    r"""Policy condition script variables"""


class GetCustomFieldsPolicyConditionScripts(BaseModel):
    r"""Policy condition script"""

    script_id: Annotated[Optional[int], pydantic.Field(alias="scriptId")] = None
    r"""Policy condition script id"""

    run_as: Annotated[
        Optional[GetCustomFieldsPolicyConditionRunAs], pydantic.Field(alias="runAs")
    ] = GetCustomFieldsPolicyConditionRunAs.SYSTEM
    r"""Policy condition script runAs"""

    script_param: Annotated[Optional[str], pydantic.Field(alias="scriptParam")] = None
    r"""Policy condition script parameter"""

    script_variables: Annotated[
        Optional[List[GetCustomFieldsPolicyConditionScriptVariables]],
        pydantic.Field(alias="scriptVariables"),
    ] = None
    r"""Policy condition script variables"""


class GetCustomFieldsPolicyConditionNotificationAction(str, Enum):
    r"""Policy condition notification action"""

    NONE = "NONE"
    SEND = "SEND"


class GetCustomFieldsPolicyConditionInheritanceTypedDict(TypedDict):
    r"""Policy condition inheritance status"""

    inherited: NotRequired[bool]
    r"""Is policy condition inherited"""
    overridden: NotRequired[bool]
    r"""Is policy condition overridden"""
    source_policy_id: NotRequired[int]
    r"""Parent policy Id"""


class GetCustomFieldsPolicyConditionInheritance(BaseModel):
    r"""Policy condition inheritance status"""

    inherited: Optional[bool] = None
    r"""Is policy condition inherited"""

    overridden: Optional[bool] = None
    r"""Is policy condition overridden"""

    source_policy_id: Annotated[
        Optional[int], pydantic.Field(alias="sourcePolicyId")
    ] = None
    r"""Parent policy Id"""


class GetCustomFieldsPolicyConditionOperator(str, Enum):
    r"""Custom field operator"""

    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    LESS_THAN = "LESS_THAN"
    LESS_OR_EQUAL_THAN = "LESS_OR_EQUAL_THAN"
    GREATER_THAN = "GREATER_THAN"
    GREATER_OR_EQUAL_THAN = "GREATER_OR_EQUAL_THAN"
    IS_NOT_NULL = "IS_NOT_NULL"
    CONTAINS = "CONTAINS"
    CONTAINS_NONE = "CONTAINS_NONE"
    CONTAINS_ANY = "CONTAINS_ANY"


class GetCustomFieldsPolicyConditionMatchAllTypedDict(TypedDict):
    r"""Policy condition custom field"""

    field_name: str
    r"""Custom field name"""
    operator: GetCustomFieldsPolicyConditionOperator
    r"""Custom field operator"""
    value: str
    r"""Custom field value"""


class GetCustomFieldsPolicyConditionMatchAll(BaseModel):
    r"""Policy condition custom field"""

    field_name: Annotated[str, pydantic.Field(alias="fieldName")]
    r"""Custom field name"""

    operator: GetCustomFieldsPolicyConditionOperator
    r"""Custom field operator"""

    value: str
    r"""Custom field value"""


class GetCustomFieldsPolicyConditionManagementOperator(str, Enum):
    r"""Custom field operator"""

    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    LESS_THAN = "LESS_THAN"
    LESS_OR_EQUAL_THAN = "LESS_OR_EQUAL_THAN"
    GREATER_THAN = "GREATER_THAN"
    GREATER_OR_EQUAL_THAN = "GREATER_OR_EQUAL_THAN"
    IS_NOT_NULL = "IS_NOT_NULL"
    CONTAINS = "CONTAINS"
    CONTAINS_NONE = "CONTAINS_NONE"
    CONTAINS_ANY = "CONTAINS_ANY"


class GetCustomFieldsPolicyConditionMatchAnyTypedDict(TypedDict):
    r"""Policy condition custom field"""

    field_name: str
    r"""Custom field name"""
    operator: GetCustomFieldsPolicyConditionManagementOperator
    r"""Custom field operator"""
    value: str
    r"""Custom field value"""


class GetCustomFieldsPolicyConditionMatchAny(BaseModel):
    r"""Policy condition custom field"""

    field_name: Annotated[str, pydantic.Field(alias="fieldName")]
    r"""Custom field name"""

    operator: GetCustomFieldsPolicyConditionManagementOperator
    r"""Custom field operator"""

    value: str
    r"""Custom field value"""


class GetCustomFieldsPolicyConditionResponseBodyTypedDict(TypedDict):
    r"""Custom fields policy condition response payload"""

    id: NotRequired[str]
    r"""Policy condition id"""
    condition_name: NotRequired[str]
    r"""Policy condition name"""
    display_name: NotRequired[str]
    r"""Policy condition display name"""
    enabled: NotRequired[bool]
    r"""Policy condition enabled"""
    severity: NotRequired[GetCustomFieldsPolicyConditionSeverity]
    r"""Policy condition severity"""
    priority: NotRequired[GetCustomFieldsPolicyConditionPriority]
    r"""Policy condition priority"""
    channels: NotRequired[List[int]]
    r"""Policy condition notification channels"""
    scripts: NotRequired[List[GetCustomFieldsPolicyConditionScriptsTypedDict]]
    r"""Policy condition scripts"""
    notification_action: NotRequired[GetCustomFieldsPolicyConditionNotificationAction]
    r"""Policy condition notification action"""
    notify_on_reset: NotRequired[bool]
    r"""Policy condition notify on reset"""
    reset_threshold: NotRequired[int]
    r"""Policy condition reset threshold (seconds)"""
    inheritance: NotRequired[GetCustomFieldsPolicyConditionInheritanceTypedDict]
    r"""Policy condition inheritance status"""
    match_all: NotRequired[List[GetCustomFieldsPolicyConditionMatchAllTypedDict]]
    r"""Custom field value must meet all conditions"""
    match_any: NotRequired[List[GetCustomFieldsPolicyConditionMatchAnyTypedDict]]
    r"""Custom field value must meet any conditions"""


class GetCustomFieldsPolicyConditionResponseBody(BaseModel):
    r"""Custom fields policy condition response payload"""

    id: Optional[str] = None
    r"""Policy condition id"""

    condition_name: Annotated[Optional[str], pydantic.Field(alias="conditionName")] = (
        None
    )
    r"""Policy condition name"""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""Policy condition display name"""

    enabled: Optional[bool] = None
    r"""Policy condition enabled"""

    severity: Optional[GetCustomFieldsPolicyConditionSeverity] = None
    r"""Policy condition severity"""

    priority: Optional[GetCustomFieldsPolicyConditionPriority] = None
    r"""Policy condition priority"""

    channels: Optional[List[int]] = None
    r"""Policy condition notification channels"""

    scripts: Optional[List[GetCustomFieldsPolicyConditionScripts]] = None
    r"""Policy condition scripts"""

    notification_action: Annotated[
        Optional[GetCustomFieldsPolicyConditionNotificationAction],
        pydantic.Field(alias="notificationAction"),
    ] = None
    r"""Policy condition notification action"""

    notify_on_reset: Annotated[
        Optional[bool], pydantic.Field(alias="notifyOnReset")
    ] = None
    r"""Policy condition notify on reset"""

    reset_threshold: Annotated[
        Optional[int], pydantic.Field(alias="resetThreshold")
    ] = None
    r"""Policy condition reset threshold (seconds)"""

    inheritance: Optional[GetCustomFieldsPolicyConditionInheritance] = None
    r"""Policy condition inheritance status"""

    match_all: Annotated[
        Optional[List[GetCustomFieldsPolicyConditionMatchAll]],
        pydantic.Field(alias="matchAll"),
    ] = None
    r"""Custom field value must meet all conditions"""

    match_any: Annotated[
        Optional[List[GetCustomFieldsPolicyConditionMatchAny]],
        pydantic.Field(alias="matchAny"),
    ] = None
    r"""Custom field value must meet any conditions"""
