"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDeviceVolumesRequestTypedDict(TypedDict):
    id: int
    r"""Device identifier"""
    include: NotRequired[str]
    r"""Additional information to include (bl - BitLocker status)"""


class GetDeviceVolumesRequest(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Device identifier"""

    include: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Additional information to include (bl - BitLocker status)"""


class ConversionStatus(str, Enum):
    r"""Volume encryption or decryption status."""

    FULLY_DECRYPTED = "FULLY_DECRYPTED"
    FULLY_ENCRYPTED = "FULLY_ENCRYPTED"
    ENCRYPTION_IN_PROGRESS = "ENCRYPTION_IN_PROGRESS"
    DECRYPTION_IN_PROGRESS = "DECRYPTION_IN_PROGRESS"
    ENCRYPTION_PAUSED = "ENCRYPTION_PAUSED"
    DECRYPTION_PAUSED = "DECRYPTION_PAUSED"
    UNKNOWN = "UNKNOWN"


class EncryptionMethod(str, Enum):
    r"""Indicated the encryption algorithm and key size used on the volume"""

    NONE = "NONE"
    AES_128_WITH_DIFFUSER = "AES_128_WITH_DIFFUSER"
    AES_256_WITH_DIFFUSER = "AES_256_WITH_DIFFUSER"
    AES_128 = "AES_128"
    AES_256 = "AES_256"
    HARDWARE_ENCRYPTION = "HARDWARE_ENCRYPTION"
    XTS_AES_128 = "XTS_AES_128"
    XTS_AES_256 = "XTS_AES_256"
    UNKNOWN = "UNKNOWN"


class ProtectionStatus(str, Enum):
    r"""indicates whether the volume and its encryption key (if any) are secured."""

    UNPROTECTED = "UNPROTECTED"
    PROTECTED = "PROTECTED"
    UNKNOWN = "UNKNOWN"
    PENDING = "PENDING"


class LockStatus(str, Enum):
    r"""Indicates whether the contents of the volume are accessible from Windows"""

    UNKNOWN = "UNKNOWN"
    UNLOCKED = "UNLOCKED"
    LOCKED = "LOCKED"


class BitLockerStatusTypedDict(TypedDict):
    r"""BitLocker Status"""

    conversion_status: NotRequired[ConversionStatus]
    r"""Volume encryption or decryption status."""
    encryption_method: NotRequired[EncryptionMethod]
    r"""Indicated the encryption algorithm and key size used on the volume"""
    protection_status: NotRequired[ProtectionStatus]
    r"""indicates whether the volume and its encryption key (if any) are secured."""
    lock_status: NotRequired[LockStatus]
    r"""Indicates whether the contents of the volume are accessible from Windows"""
    initialized_for_protection: NotRequired[bool]
    r"""Is initialized for protection"""


class BitLockerStatus(BaseModel):
    r"""BitLocker Status"""

    conversion_status: Annotated[
        Optional[ConversionStatus], pydantic.Field(alias="conversionStatus")
    ] = None
    r"""Volume encryption or decryption status."""

    encryption_method: Annotated[
        Optional[EncryptionMethod], pydantic.Field(alias="encryptionMethod")
    ] = None
    r"""Indicated the encryption algorithm and key size used on the volume"""

    protection_status: Annotated[
        Optional[ProtectionStatus], pydantic.Field(alias="protectionStatus")
    ] = None
    r"""indicates whether the volume and its encryption key (if any) are secured."""

    lock_status: Annotated[Optional[LockStatus], pydantic.Field(alias="lockStatus")] = (
        None
    )
    r"""Indicates whether the contents of the volume are accessible from Windows"""

    initialized_for_protection: Annotated[
        Optional[bool], pydantic.Field(alias="initializedForProtection")
    ] = None
    r"""Is initialized for protection"""


class GetDeviceVolumesResponseBodyTypedDict(TypedDict):
    r"""Disk Volumes"""

    name: NotRequired[str]
    r"""Name"""
    drive_letter: NotRequired[str]
    r"""Drive Letter"""
    label: NotRequired[str]
    r"""Volume Label"""
    device_type: NotRequired[str]
    r"""Device Type"""
    file_system: NotRequired[str]
    r"""File System Type"""
    auto_mount: NotRequired[bool]
    r"""Automatically Mounted"""
    compressed: NotRequired[bool]
    r"""Compressed"""
    capacity: NotRequired[int]
    r"""Capacity (bytes)"""
    free_space: NotRequired[int]
    r"""Free Space (bytes)"""
    serial_number: NotRequired[str]
    r"""Serial Number"""
    bit_locker_status: NotRequired[BitLockerStatusTypedDict]
    r"""BitLocker Status"""


class GetDeviceVolumesResponseBody(BaseModel):
    r"""Disk Volumes"""

    name: Optional[str] = None
    r"""Name"""

    drive_letter: Annotated[Optional[str], pydantic.Field(alias="driveLetter")] = None
    r"""Drive Letter"""

    label: Optional[str] = None
    r"""Volume Label"""

    device_type: Annotated[Optional[str], pydantic.Field(alias="deviceType")] = None
    r"""Device Type"""

    file_system: Annotated[Optional[str], pydantic.Field(alias="fileSystem")] = None
    r"""File System Type"""

    auto_mount: Annotated[Optional[bool], pydantic.Field(alias="autoMount")] = None
    r"""Automatically Mounted"""

    compressed: Optional[bool] = None
    r"""Compressed"""

    capacity: Optional[int] = None
    r"""Capacity (bytes)"""

    free_space: Annotated[Optional[int], pydantic.Field(alias="freeSpace")] = None
    r"""Free Space (bytes)"""

    serial_number: Annotated[Optional[str], pydantic.Field(alias="serialNumber")] = None
    r"""Serial Number"""

    bit_locker_status: Annotated[
        Optional[BitLockerStatus], pydantic.Field(alias="bitLockerStatus")
    ] = None
    r"""BitLocker Status"""
