"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetDevicesDetailedRequestTypedDict(TypedDict):
    df: NotRequired[str]
    r"""Device filter"""
    page_size: NotRequired[int]
    after: NotRequired[int]


class GetDevicesDetailedRequest(BaseModel):
    df: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Device filter"""

    page_size: Annotated[
        Optional[int],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    after: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None


class GetDevicesDetailedNodeClass(str, Enum):
    r"""Node Class"""

    WINDOWS_SERVER = "WINDOWS_SERVER"
    WINDOWS_WORKSTATION = "WINDOWS_WORKSTATION"
    LINUX_WORKSTATION = "LINUX_WORKSTATION"
    MAC = "MAC"
    ANDROID = "ANDROID"
    APPLE_IOS = "APPLE_IOS"
    APPLE_IPADOS = "APPLE_IPADOS"
    VMWARE_VM_HOST = "VMWARE_VM_HOST"
    VMWARE_VM_GUEST = "VMWARE_VM_GUEST"
    HYPERV_VMM_HOST = "HYPERV_VMM_HOST"
    HYPERV_VMM_GUEST = "HYPERV_VMM_GUEST"
    LINUX_SERVER = "LINUX_SERVER"
    MAC_SERVER = "MAC_SERVER"
    CLOUD_MONITOR_TARGET = "CLOUD_MONITOR_TARGET"
    NMS_SWITCH = "NMS_SWITCH"
    NMS_ROUTER = "NMS_ROUTER"
    NMS_FIREWALL = "NMS_FIREWALL"
    NMS_PRIVATE_NETWORK_GATEWAY = "NMS_PRIVATE_NETWORK_GATEWAY"
    NMS_PRINTER = "NMS_PRINTER"
    NMS_SCANNER = "NMS_SCANNER"
    NMS_DIAL_MANAGER = "NMS_DIAL_MANAGER"
    NMS_WAP = "NMS_WAP"
    NMS_IPSLA = "NMS_IPSLA"
    NMS_COMPUTER = "NMS_COMPUTER"
    NMS_VM_HOST = "NMS_VM_HOST"
    NMS_APPLIANCE = "NMS_APPLIANCE"
    NMS_OTHER = "NMS_OTHER"
    NMS_SERVER = "NMS_SERVER"
    NMS_PHONE = "NMS_PHONE"
    NMS_VIRTUAL_MACHINE = "NMS_VIRTUAL_MACHINE"
    NMS_NETWORK_MANAGEMENT_AGENT = "NMS_NETWORK_MANAGEMENT_AGENT"


class GetDevicesDetailedApprovalStatus(str, Enum):
    r"""Approval Status"""

    PENDING = "PENDING"
    APPROVED = "APPROVED"


class GetDevicesDetailedFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetDevicesDetailedFields(BaseModel):
    r"""Custom Fields"""


class GetDevicesDetailedStatus(str, Enum):
    r"""Maintenance mode status"""

    PENDING = "PENDING"
    IN_MAINTENANCE = "IN_MAINTENANCE"
    FAILED = "FAILED"


class GetDevicesDetailedMaintenanceTypedDict(TypedDict):
    r"""Maintenance mode status"""

    status: NotRequired[GetDevicesDetailedStatus]
    r"""Maintenance mode status"""
    start: NotRequired[float]
    r"""Maintenance mode start time"""
    end: NotRequired[float]
    r"""Maintenance mode end time"""


class GetDevicesDetailedMaintenance(BaseModel):
    r"""Maintenance mode status"""

    status: Optional[GetDevicesDetailedStatus] = None
    r"""Maintenance mode status"""

    start: Optional[float] = None
    r"""Maintenance mode start time"""

    end: Optional[float] = None
    r"""Maintenance mode end time"""


class GetDevicesDetailedNodeApprovalMode(str, Enum):
    r"""Device Approval Mode"""

    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    REJECT = "REJECT"


class GetDevicesDetailedSystemFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetDevicesDetailedSystemFields(BaseModel):
    r"""Custom Fields"""


class GetDevicesDetailedOrganizationTypedDict(TypedDict):
    r"""Organization"""

    name: NotRequired[str]
    r"""Organization full name"""
    description: NotRequired[str]
    r"""Organization Description"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    node_approval_mode: NotRequired[GetDevicesDetailedNodeApprovalMode]
    r"""Device Approval Mode"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, GetDevicesDetailedSystemFieldsTypedDict]]
    r"""Custom Fields"""
    id: NotRequired[int]
    r"""Organization identifier"""


class GetDevicesDetailedOrganization(BaseModel):
    r"""Organization"""

    name: Optional[str] = None
    r"""Organization full name"""

    description: Optional[str] = None
    r"""Organization Description"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    node_approval_mode: Annotated[
        Optional[GetDevicesDetailedNodeApprovalMode],
        pydantic.Field(alias="nodeApprovalMode"),
    ] = None
    r"""Device Approval Mode"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetDevicesDetailedSystemFields]] = None
    r"""Custom Fields"""

    id: Optional[int] = None
    r"""Organization identifier"""


class GetDevicesDetailedSystemResponseFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseFields(BaseModel):
    r"""Custom Fields"""


class GetDevicesDetailedLocationTypedDict(TypedDict):
    r"""Location"""

    name: NotRequired[str]
    r"""Location name"""
    address: NotRequired[str]
    r"""Address"""
    description: NotRequired[str]
    r"""Description"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, GetDevicesDetailedSystemResponseFieldsTypedDict]]
    r"""Custom Fields"""
    id: NotRequired[int]
    r"""Location identifier"""


class GetDevicesDetailedLocation(BaseModel):
    r"""Location"""

    name: Optional[str] = None
    r"""Location name"""

    address: Optional[str] = None
    r"""Address"""

    description: Optional[str] = None
    r"""Description"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetDevicesDetailedSystemResponseFields]] = None
    r"""Custom Fields"""

    id: Optional[int] = None
    r"""Location identifier"""


class GetDevicesDetailedSystemNodeClass(str, Enum):
    r"""Node Class"""

    WINDOWS_SERVER = "WINDOWS_SERVER"
    WINDOWS_WORKSTATION = "WINDOWS_WORKSTATION"
    LINUX_WORKSTATION = "LINUX_WORKSTATION"
    MAC = "MAC"
    ANDROID = "ANDROID"
    APPLE_IOS = "APPLE_IOS"
    APPLE_IPADOS = "APPLE_IPADOS"
    VMWARE_VM_HOST = "VMWARE_VM_HOST"
    VMWARE_VM_GUEST = "VMWARE_VM_GUEST"
    HYPERV_VMM_HOST = "HYPERV_VMM_HOST"
    HYPERV_VMM_GUEST = "HYPERV_VMM_GUEST"
    LINUX_SERVER = "LINUX_SERVER"
    MAC_SERVER = "MAC_SERVER"
    CLOUD_MONITOR_TARGET = "CLOUD_MONITOR_TARGET"
    NMS_SWITCH = "NMS_SWITCH"
    NMS_ROUTER = "NMS_ROUTER"
    NMS_FIREWALL = "NMS_FIREWALL"
    NMS_PRIVATE_NETWORK_GATEWAY = "NMS_PRIVATE_NETWORK_GATEWAY"
    NMS_PRINTER = "NMS_PRINTER"
    NMS_SCANNER = "NMS_SCANNER"
    NMS_DIAL_MANAGER = "NMS_DIAL_MANAGER"
    NMS_WAP = "NMS_WAP"
    NMS_IPSLA = "NMS_IPSLA"
    NMS_COMPUTER = "NMS_COMPUTER"
    NMS_VM_HOST = "NMS_VM_HOST"
    NMS_APPLIANCE = "NMS_APPLIANCE"
    NMS_OTHER = "NMS_OTHER"
    NMS_SERVER = "NMS_SERVER"
    NMS_PHONE = "NMS_PHONE"
    NMS_VIRTUAL_MACHINE = "NMS_VIRTUAL_MACHINE"
    NMS_NETWORK_MANAGEMENT_AGENT = "NMS_NETWORK_MANAGEMENT_AGENT"


class GetDevicesDetailedSystemResponseDefaultFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseDefaultFields(BaseModel):
    r"""Custom Fields"""


class GetDevicesDetailedRolePolicyTypedDict(TypedDict):
    r"""Assigned policy (overrides organization and location policy mapping)"""

    id: NotRequired[int]
    r"""Policy identifier"""
    parent_policy_id: NotRequired[int]
    r"""Parent Policy identifier"""
    name: NotRequired[str]
    r"""Name"""
    description: NotRequired[str]
    r"""Description"""
    node_class: NotRequired[GetDevicesDetailedSystemNodeClass]
    r"""Node Class"""
    updated: NotRequired[float]
    r"""Last update timestamp"""
    node_class_default: NotRequired[bool]
    r"""Is Default Policy for Node Class"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[
        Dict[str, GetDevicesDetailedSystemResponseDefaultFieldsTypedDict]
    ]
    r"""Custom Fields"""


class GetDevicesDetailedRolePolicy(BaseModel):
    r"""Assigned policy (overrides organization and location policy mapping)"""

    id: Optional[int] = None
    r"""Policy identifier"""

    parent_policy_id: Annotated[
        Optional[int], pydantic.Field(alias="parentPolicyId")
    ] = None
    r"""Parent Policy identifier"""

    name: Optional[str] = None
    r"""Name"""

    description: Optional[str] = None
    r"""Description"""

    node_class: Annotated[
        Optional[GetDevicesDetailedSystemNodeClass], pydantic.Field(alias="nodeClass")
    ] = None
    r"""Node Class"""

    updated: Optional[float] = None
    r"""Last update timestamp"""

    node_class_default: Annotated[
        Optional[bool], pydantic.Field(alias="nodeClassDefault")
    ] = None
    r"""Is Default Policy for Node Class"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetDevicesDetailedSystemResponseDefaultFields]] = None
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseNodeClass(str, Enum):
    r"""Node Class"""

    WINDOWS_SERVER = "WINDOWS_SERVER"
    WINDOWS_WORKSTATION = "WINDOWS_WORKSTATION"
    LINUX_WORKSTATION = "LINUX_WORKSTATION"
    MAC = "MAC"
    ANDROID = "ANDROID"
    APPLE_IOS = "APPLE_IOS"
    APPLE_IPADOS = "APPLE_IPADOS"
    VMWARE_VM_HOST = "VMWARE_VM_HOST"
    VMWARE_VM_GUEST = "VMWARE_VM_GUEST"
    HYPERV_VMM_HOST = "HYPERV_VMM_HOST"
    HYPERV_VMM_GUEST = "HYPERV_VMM_GUEST"
    LINUX_SERVER = "LINUX_SERVER"
    MAC_SERVER = "MAC_SERVER"
    CLOUD_MONITOR_TARGET = "CLOUD_MONITOR_TARGET"
    NMS_SWITCH = "NMS_SWITCH"
    NMS_ROUTER = "NMS_ROUTER"
    NMS_FIREWALL = "NMS_FIREWALL"
    NMS_PRIVATE_NETWORK_GATEWAY = "NMS_PRIVATE_NETWORK_GATEWAY"
    NMS_PRINTER = "NMS_PRINTER"
    NMS_SCANNER = "NMS_SCANNER"
    NMS_DIAL_MANAGER = "NMS_DIAL_MANAGER"
    NMS_WAP = "NMS_WAP"
    NMS_IPSLA = "NMS_IPSLA"
    NMS_COMPUTER = "NMS_COMPUTER"
    NMS_VM_HOST = "NMS_VM_HOST"
    NMS_APPLIANCE = "NMS_APPLIANCE"
    NMS_OTHER = "NMS_OTHER"
    NMS_SERVER = "NMS_SERVER"
    NMS_PHONE = "NMS_PHONE"
    NMS_VIRTUAL_MACHINE = "NMS_VIRTUAL_MACHINE"
    NMS_NETWORK_MANAGEMENT_AGENT = "NMS_NETWORK_MANAGEMENT_AGENT"


class GetDevicesDetailedSystemResponseDefaultApplicationJSONFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseDefaultApplicationJSONFields(BaseModel):
    r"""Custom Fields"""


class GetDevicesDetailedPolicyTypedDict(TypedDict):
    r"""Assigned policy (overrides organization and location policy mapping)"""

    id: NotRequired[int]
    r"""Policy identifier"""
    parent_policy_id: NotRequired[int]
    r"""Parent Policy identifier"""
    name: NotRequired[str]
    r"""Name"""
    description: NotRequired[str]
    r"""Description"""
    node_class: NotRequired[GetDevicesDetailedSystemResponseNodeClass]
    r"""Node Class"""
    updated: NotRequired[float]
    r"""Last update timestamp"""
    node_class_default: NotRequired[bool]
    r"""Is Default Policy for Node Class"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[
        Dict[str, GetDevicesDetailedSystemResponseDefaultApplicationJSONFieldsTypedDict]
    ]
    r"""Custom Fields"""


class GetDevicesDetailedPolicy(BaseModel):
    r"""Assigned policy (overrides organization and location policy mapping)"""

    id: Optional[int] = None
    r"""Policy identifier"""

    parent_policy_id: Annotated[
        Optional[int], pydantic.Field(alias="parentPolicyId")
    ] = None
    r"""Parent Policy identifier"""

    name: Optional[str] = None
    r"""Name"""

    description: Optional[str] = None
    r"""Description"""

    node_class: Annotated[
        Optional[GetDevicesDetailedSystemResponseNodeClass],
        pydantic.Field(alias="nodeClass"),
    ] = None
    r"""Node Class"""

    updated: Optional[float] = None
    r"""Last update timestamp"""

    node_class_default: Annotated[
        Optional[bool], pydantic.Field(alias="nodeClassDefault")
    ] = None
    r"""Is Default Policy for Node Class"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[
        Dict[str, GetDevicesDetailedSystemResponseDefaultApplicationJSONFields]
    ] = None
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseDefaultNodeClass(str, Enum):
    r"""Node Class"""

    WINDOWS_SERVER = "WINDOWS_SERVER"
    WINDOWS_WORKSTATION = "WINDOWS_WORKSTATION"
    LINUX_WORKSTATION = "LINUX_WORKSTATION"
    MAC = "MAC"
    ANDROID = "ANDROID"
    APPLE_IOS = "APPLE_IOS"
    APPLE_IPADOS = "APPLE_IPADOS"
    VMWARE_VM_HOST = "VMWARE_VM_HOST"
    VMWARE_VM_GUEST = "VMWARE_VM_GUEST"
    HYPERV_VMM_HOST = "HYPERV_VMM_HOST"
    HYPERV_VMM_GUEST = "HYPERV_VMM_GUEST"
    LINUX_SERVER = "LINUX_SERVER"
    MAC_SERVER = "MAC_SERVER"
    CLOUD_MONITOR_TARGET = "CLOUD_MONITOR_TARGET"
    NMS_SWITCH = "NMS_SWITCH"
    NMS_ROUTER = "NMS_ROUTER"
    NMS_FIREWALL = "NMS_FIREWALL"
    NMS_PRIVATE_NETWORK_GATEWAY = "NMS_PRIVATE_NETWORK_GATEWAY"
    NMS_PRINTER = "NMS_PRINTER"
    NMS_SCANNER = "NMS_SCANNER"
    NMS_DIAL_MANAGER = "NMS_DIAL_MANAGER"
    NMS_WAP = "NMS_WAP"
    NMS_IPSLA = "NMS_IPSLA"
    NMS_COMPUTER = "NMS_COMPUTER"
    NMS_VM_HOST = "NMS_VM_HOST"
    NMS_APPLIANCE = "NMS_APPLIANCE"
    NMS_OTHER = "NMS_OTHER"
    NMS_SERVER = "NMS_SERVER"
    NMS_PHONE = "NMS_PHONE"
    NMS_VIRTUAL_MACHINE = "NMS_VIRTUAL_MACHINE"
    NMS_NETWORK_MANAGEMENT_AGENT = "NMS_NETWORK_MANAGEMENT_AGENT"


class GetDevicesDetailedChassisType(str, Enum):
    r"""Chassis Type"""

    UNKNOWN = "UNKNOWN"
    DESKTOP = "DESKTOP"
    LAPTOP = "LAPTOP"
    MOBILE = "MOBILE"


class GetDevicesDetailedSystemResponseDefaultApplicationJSONResponseBodyFieldsTypedDict(
    TypedDict
):
    r"""Custom Fields"""


class GetDevicesDetailedSystemResponseDefaultApplicationJSONResponseBodyFields(
    BaseModel
):
    r"""Custom Fields"""


class GetDevicesDetailedRoleTypedDict(TypedDict):
    r"""Device Role"""

    id: NotRequired[int]
    r"""Device Role identifier"""
    name: NotRequired[str]
    r"""Name"""
    description: NotRequired[str]
    r"""Description"""
    node_class: NotRequired[GetDevicesDetailedSystemResponseDefaultNodeClass]
    r"""Node Class"""
    custom: NotRequired[bool]
    r"""Is custom node role?"""
    chassis_type: NotRequired[GetDevicesDetailedChassisType]
    r"""Chassis Type"""
    created: NotRequired[float]
    r"""Date created"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[
        Dict[
            str,
            GetDevicesDetailedSystemResponseDefaultApplicationJSONResponseBodyFieldsTypedDict,
        ]
    ]
    r"""Custom Fields"""


class GetDevicesDetailedRole(BaseModel):
    r"""Device Role"""

    id: Optional[int] = None
    r"""Device Role identifier"""

    name: Optional[str] = None
    r"""Name"""

    description: Optional[str] = None
    r"""Description"""

    node_class: Annotated[
        Optional[GetDevicesDetailedSystemResponseDefaultNodeClass],
        pydantic.Field(alias="nodeClass"),
    ] = None
    r"""Node Class"""

    custom: Optional[bool] = None
    r"""Is custom node role?"""

    chassis_type: Annotated[
        Optional[GetDevicesDetailedChassisType], pydantic.Field(alias="chassisType")
    ] = None
    r"""Chassis Type"""

    created: Optional[float] = None
    r"""Date created"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[
        Dict[
            str,
            GetDevicesDetailedSystemResponseDefaultApplicationJSONResponseBodyFields,
        ]
    ] = None
    r"""Custom Fields"""


class GetDevicesDetailedBackupUsageTypedDict(TypedDict):
    r"""Device Backup Usage"""

    revisions_current_size: NotRequired[int]
    r"""Revisions current size"""
    revisions_previous_size: NotRequired[int]
    r"""Revisions previous size"""
    revisions_deleted_size: NotRequired[int]
    r"""Revisions deleted size"""
    local_file_folder_size: NotRequired[int]
    r"""Revisions local file folder size"""
    local_image_size: NotRequired[int]
    r"""Revisions local image size"""
    local_image_v2_size: NotRequired[int]
    r"""Revisions local image v2 size"""
    cloud_file_folder_size: NotRequired[int]
    r"""Revisions cloud file folder size"""
    cloud_image_size: NotRequired[int]
    r"""Revisions cloud image size"""
    cloud_image_v2_size: NotRequired[int]
    r"""Revisions cloud image v2 size"""
    last_successful_backup_job: NotRequired[float]
    r"""Last successful job. This is provided when the 'includeLastBackupJobTimes' query parameter is set to 'true'"""
    last_failed_backup_job: NotRequired[float]
    r"""Last failed job. This is provided when the 'includeLastBackupJobTimes' query parameter is set to 'true'"""
    revisions_total_size: NotRequired[int]
    r"""Revisions total size"""
    cloud_total_size: NotRequired[int]
    r"""Revisions cloud total size"""
    local_total_size: NotRequired[int]
    r"""Revisions local total size"""


class GetDevicesDetailedBackupUsage(BaseModel):
    r"""Device Backup Usage"""

    revisions_current_size: Annotated[
        Optional[int], pydantic.Field(alias="revisionsCurrentSize")
    ] = None
    r"""Revisions current size"""

    revisions_previous_size: Annotated[
        Optional[int], pydantic.Field(alias="revisionsPreviousSize")
    ] = None
    r"""Revisions previous size"""

    revisions_deleted_size: Annotated[
        Optional[int], pydantic.Field(alias="revisionsDeletedSize")
    ] = None
    r"""Revisions deleted size"""

    local_file_folder_size: Annotated[
        Optional[int], pydantic.Field(alias="localFileFolderSize")
    ] = None
    r"""Revisions local file folder size"""

    local_image_size: Annotated[
        Optional[int], pydantic.Field(alias="localImageSize")
    ] = None
    r"""Revisions local image size"""

    local_image_v2_size: Annotated[
        Optional[int], pydantic.Field(alias="localImageV2Size")
    ] = None
    r"""Revisions local image v2 size"""

    cloud_file_folder_size: Annotated[
        Optional[int], pydantic.Field(alias="cloudFileFolderSize")
    ] = None
    r"""Revisions cloud file folder size"""

    cloud_image_size: Annotated[
        Optional[int], pydantic.Field(alias="cloudImageSize")
    ] = None
    r"""Revisions cloud image size"""

    cloud_image_v2_size: Annotated[
        Optional[int], pydantic.Field(alias="cloudImageV2Size")
    ] = None
    r"""Revisions cloud image v2 size"""

    last_successful_backup_job: Annotated[
        Optional[float], pydantic.Field(alias="lastSuccessfulBackupJob")
    ] = None
    r"""Last successful job. This is provided when the 'includeLastBackupJobTimes' query parameter is set to 'true'"""

    last_failed_backup_job: Annotated[
        Optional[float], pydantic.Field(alias="lastFailedBackupJob")
    ] = None
    r"""Last failed job. This is provided when the 'includeLastBackupJobTimes' query parameter is set to 'true'"""

    revisions_total_size: Annotated[
        Optional[int], pydantic.Field(alias="revisionsTotalSize")
    ] = None
    r"""Revisions total size"""

    cloud_total_size: Annotated[
        Optional[int], pydantic.Field(alias="cloudTotalSize")
    ] = None
    r"""Revisions cloud total size"""

    local_total_size: Annotated[
        Optional[int], pydantic.Field(alias="localTotalSize")
    ] = None
    r"""Revisions local total size"""


class GetDevicesDetailedWarrantyTypedDict(TypedDict):
    r"""Warranty Info"""

    start_date: NotRequired[float]
    r"""Warranty Start Date (Seconds)"""
    end_date: NotRequired[float]
    r"""Warranty End Date (Seconds)"""
    manufacturer_fulfillment_date: NotRequired[float]
    r"""Manufacturer Fulfillment Date"""


class GetDevicesDetailedWarranty(BaseModel):
    r"""Warranty Info"""

    start_date: Annotated[Optional[float], pydantic.Field(alias="startDate")] = None
    r"""Warranty Start Date (Seconds)"""

    end_date: Annotated[Optional[float], pydantic.Field(alias="endDate")] = None
    r"""Warranty End Date (Seconds)"""

    manufacturer_fulfillment_date: Annotated[
        Optional[float], pydantic.Field(alias="manufacturerFulfillmentDate")
    ] = None
    r"""Manufacturer Fulfillment Date"""


class GetDevicesDetailedReferencesTypedDict(TypedDict):
    r"""Expanded entity references"""

    organization: NotRequired[GetDevicesDetailedOrganizationTypedDict]
    r"""Organization"""
    location: NotRequired[GetDevicesDetailedLocationTypedDict]
    r"""Location"""
    role_policy: NotRequired[GetDevicesDetailedRolePolicyTypedDict]
    r"""Assigned policy (overrides organization and location policy mapping)"""
    policy: NotRequired[GetDevicesDetailedPolicyTypedDict]
    r"""Assigned policy (overrides organization and location policy mapping)"""
    role: NotRequired[GetDevicesDetailedRoleTypedDict]
    r"""Device Role"""
    backup_usage: NotRequired[GetDevicesDetailedBackupUsageTypedDict]
    r"""Device Backup Usage"""
    warranty: NotRequired[GetDevicesDetailedWarrantyTypedDict]
    r"""Warranty Info"""


class GetDevicesDetailedReferences(BaseModel):
    r"""Expanded entity references"""

    organization: Optional[GetDevicesDetailedOrganization] = None
    r"""Organization"""

    location: Optional[GetDevicesDetailedLocation] = None
    r"""Location"""

    role_policy: Annotated[
        Optional[GetDevicesDetailedRolePolicy], pydantic.Field(alias="rolePolicy")
    ] = None
    r"""Assigned policy (overrides organization and location policy mapping)"""

    policy: Optional[GetDevicesDetailedPolicy] = None
    r"""Assigned policy (overrides organization and location policy mapping)"""

    role: Optional[GetDevicesDetailedRole] = None
    r"""Device Role"""

    backup_usage: Annotated[
        Optional[GetDevicesDetailedBackupUsage], pydantic.Field(alias="backupUsage")
    ] = None
    r"""Device Backup Usage"""

    warranty: Optional[GetDevicesDetailedWarranty] = None
    r"""Warranty Info"""


class GetDevicesDetailedNotesTypedDict(TypedDict):
    r"""Device Notes"""

    text: NotRequired[str]
    r"""Note text"""


class GetDevicesDetailedNotes(BaseModel):
    r"""Device Notes"""

    text: Optional[str] = None
    r"""Note text"""


class GetDevicesDetailedResponseBodyTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Node (Device) identifier"""
    parent_device_id: NotRequired[int]
    r"""Parent Node identifier"""
    organization_id: NotRequired[int]
    r"""Organization identifier"""
    location_id: NotRequired[int]
    r"""Location identifier"""
    node_class: NotRequired[GetDevicesDetailedNodeClass]
    r"""Node Class"""
    node_role_id: NotRequired[int]
    r"""Node Role identifier"""
    role_policy_id: NotRequired[int]
    r"""Node Role policy ID based on organization and location Policy Mapping"""
    policy_id: NotRequired[int]
    r"""Assigned policy ID (overrides organization and location policy mapping)"""
    approval_status: NotRequired[GetDevicesDetailedApprovalStatus]
    r"""Approval Status"""
    offline: NotRequired[bool]
    r"""Is Offline?"""
    display_name: NotRequired[str]
    r"""Display Name"""
    system_name: NotRequired[str]
    r"""System Name"""
    dns_name: NotRequired[str]
    r"""DNS Name"""
    netbios_name: NotRequired[str]
    r"""NETBIOS Name"""
    created: NotRequired[float]
    r"""Created"""
    last_contact: NotRequired[float]
    r"""Last Contact"""
    last_update: NotRequired[float]
    r"""Last data submission timestamp"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, GetDevicesDetailedFieldsTypedDict]]
    r"""Custom Fields"""
    maintenance: NotRequired[GetDevicesDetailedMaintenanceTypedDict]
    r"""Maintenance mode status"""
    references: NotRequired[GetDevicesDetailedReferencesTypedDict]
    r"""Expanded entity references"""
    ip_addresses: NotRequired[List[str]]
    r"""Device IP addresses"""
    mac_addresses: NotRequired[List[str]]
    r"""Device MAC addresses"""
    public_ip: NotRequired[str]
    r"""Device Public IP Address"""
    notes: NotRequired[List[GetDevicesDetailedNotesTypedDict]]
    r"""Device Notes"""
    device_type: NotRequired[str]


class GetDevicesDetailedResponseBody(BaseModel):
    id: Optional[int] = None
    r"""Node (Device) identifier"""

    parent_device_id: Annotated[
        Optional[int], pydantic.Field(alias="parentDeviceId")
    ] = None
    r"""Parent Node identifier"""

    organization_id: Annotated[
        Optional[int], pydantic.Field(alias="organizationId")
    ] = None
    r"""Organization identifier"""

    location_id: Annotated[Optional[int], pydantic.Field(alias="locationId")] = None
    r"""Location identifier"""

    node_class: Annotated[
        Optional[GetDevicesDetailedNodeClass], pydantic.Field(alias="nodeClass")
    ] = None
    r"""Node Class"""

    node_role_id: Annotated[Optional[int], pydantic.Field(alias="nodeRoleId")] = None
    r"""Node Role identifier"""

    role_policy_id: Annotated[Optional[int], pydantic.Field(alias="rolePolicyId")] = (
        None
    )
    r"""Node Role policy ID based on organization and location Policy Mapping"""

    policy_id: Annotated[Optional[int], pydantic.Field(alias="policyId")] = None
    r"""Assigned policy ID (overrides organization and location policy mapping)"""

    approval_status: Annotated[
        Optional[GetDevicesDetailedApprovalStatus],
        pydantic.Field(alias="approvalStatus"),
    ] = None
    r"""Approval Status"""

    offline: Optional[bool] = None
    r"""Is Offline?"""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""Display Name"""

    system_name: Annotated[Optional[str], pydantic.Field(alias="systemName")] = None
    r"""System Name"""

    dns_name: Annotated[Optional[str], pydantic.Field(alias="dnsName")] = None
    r"""DNS Name"""

    netbios_name: Annotated[Optional[str], pydantic.Field(alias="netbiosName")] = None
    r"""NETBIOS Name"""

    created: Optional[float] = None
    r"""Created"""

    last_contact: Annotated[Optional[float], pydantic.Field(alias="lastContact")] = None
    r"""Last Contact"""

    last_update: Annotated[Optional[float], pydantic.Field(alias="lastUpdate")] = None
    r"""Last data submission timestamp"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetDevicesDetailedFields]] = None
    r"""Custom Fields"""

    maintenance: Optional[GetDevicesDetailedMaintenance] = None
    r"""Maintenance mode status"""

    references: Optional[GetDevicesDetailedReferences] = None
    r"""Expanded entity references"""

    ip_addresses: Annotated[
        Optional[List[str]], pydantic.Field(alias="ipAddresses")
    ] = None
    r"""Device IP addresses"""

    mac_addresses: Annotated[
        Optional[List[str]], pydantic.Field(alias="macAddresses")
    ] = None
    r"""Device MAC addresses"""

    public_ip: Annotated[Optional[str], pydantic.Field(alias="publicIP")] = None
    r"""Device Public IP Address"""

    notes: Optional[List[GetDevicesDetailedNotes]] = None
    r"""Device Notes"""

    device_type: Annotated[Optional[str], pydantic.Field(alias="deviceType")] = None
