"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetNodeCustomFields2RequestTypedDict(TypedDict):
    id: int
    location_id: int
    with_inheritance: NotRequired[bool]
    r"""Retrieve values using definition scope hierarchy"""


class GetNodeCustomFields2Request(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    location_id: Annotated[
        int,
        pydantic.Field(alias="locationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    with_inheritance: Annotated[
        Optional[bool],
        pydantic.Field(alias="withInheritance"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Retrieve values using definition scope hierarchy"""


class GetNodeCustomFields2ResponseBodyTypedDict(TypedDict):
    pass


class GetNodeCustomFields2ResponseBody(BaseModel):
    pass
