"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetOrganizationsDetailedRequestTypedDict(TypedDict):
    page_size: NotRequired[int]
    r"""Limit number of organizations to return"""
    after: NotRequired[int]
    r"""Last Organization Identifier from previous page"""
    of: NotRequired[str]
    r"""Organization filter"""


class GetOrganizationsDetailedRequest(BaseModel):
    page_size: Annotated[
        Optional[int],
        pydantic.Field(alias="pageSize"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Limit number of organizations to return"""

    after: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Last Organization Identifier from previous page"""

    of: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Organization filter"""


class GetOrganizationsDetailedNodeApprovalMode(str, Enum):
    r"""Device Approval Mode"""

    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    REJECT = "REJECT"


class GetOrganizationsDetailedFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetOrganizationsDetailedFields(BaseModel):
    r"""Custom Fields"""


class GetOrganizationsDetailedSystemFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class GetOrganizationsDetailedSystemFields(BaseModel):
    r"""Custom Fields"""


class GetOrganizationsDetailedLocationsTypedDict(TypedDict):
    r"""Location"""

    name: NotRequired[str]
    r"""Location name"""
    address: NotRequired[str]
    r"""Address"""
    description: NotRequired[str]
    r"""Description"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, GetOrganizationsDetailedSystemFieldsTypedDict]]
    r"""Custom Fields"""
    id: NotRequired[int]
    r"""Location identifier"""


class GetOrganizationsDetailedLocations(BaseModel):
    r"""Location"""

    name: Optional[str] = None
    r"""Location name"""

    address: Optional[str] = None
    r"""Address"""

    description: Optional[str] = None
    r"""Description"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetOrganizationsDetailedSystemFields]] = None
    r"""Custom Fields"""

    id: Optional[int] = None
    r"""Location identifier"""


class GetOrganizationsDetailedPoliciesTypedDict(TypedDict):
    r"""Node role policy assignments"""

    node_role_id: NotRequired[int]
    r"""Node Role Identifier"""
    policy_id: NotRequired[int]
    r"""Policy Identifier"""


class GetOrganizationsDetailedPolicies(BaseModel):
    r"""Node role policy assignments"""

    node_role_id: Annotated[Optional[int], pydantic.Field(alias="nodeRoleId")] = None
    r"""Node Role Identifier"""

    policy_id: Annotated[Optional[int], pydantic.Field(alias="policyId")] = None
    r"""Policy Identifier"""


class GetOrganizationsDetailedOptionsTypedDict(TypedDict):
    r"""Feature options"""


class GetOrganizationsDetailedOptions(BaseModel):
    r"""Feature options"""


class GetOrganizationsDetailedTrayiconTypedDict(TypedDict):
    r"""Feature/product/integration configuration settings"""

    product: NotRequired[str]
    r"""Configured product code"""
    enabled: NotRequired[bool]
    r"""Is enabled"""
    targets: NotRequired[List[str]]
    r"""Feature deployment targets"""
    options: NotRequired[Dict[str, GetOrganizationsDetailedOptionsTypedDict]]
    r"""Feature options"""


class GetOrganizationsDetailedTrayicon(BaseModel):
    r"""Feature/product/integration configuration settings"""

    product: Optional[str] = None
    r"""Configured product code"""

    enabled: Optional[bool] = None
    r"""Is enabled"""

    targets: Optional[List[str]] = None
    r"""Feature deployment targets"""

    options: Optional[Dict[str, GetOrganizationsDetailedOptions]] = None
    r"""Feature options"""


class GetOrganizationsDetailedSystemOptionsTypedDict(TypedDict):
    r"""Feature options"""


class GetOrganizationsDetailedSystemOptions(BaseModel):
    r"""Feature options"""


class GetOrganizationsDetailedSplashtopTypedDict(TypedDict):
    r"""Feature/product/integration configuration settings"""

    product: NotRequired[str]
    r"""Configured product code"""
    enabled: NotRequired[bool]
    r"""Is enabled"""
    targets: NotRequired[List[str]]
    r"""Feature deployment targets"""
    options: NotRequired[Dict[str, GetOrganizationsDetailedSystemOptionsTypedDict]]
    r"""Feature options"""


class GetOrganizationsDetailedSplashtop(BaseModel):
    r"""Feature/product/integration configuration settings"""

    product: Optional[str] = None
    r"""Configured product code"""

    enabled: Optional[bool] = None
    r"""Is enabled"""

    targets: Optional[List[str]] = None
    r"""Feature deployment targets"""

    options: Optional[Dict[str, GetOrganizationsDetailedSystemOptions]] = None
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseOptionsTypedDict(TypedDict):
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseOptions(BaseModel):
    r"""Feature options"""


class GetOrganizationsDetailedTeamviewerTypedDict(TypedDict):
    r"""Feature/product/integration configuration settings"""

    product: NotRequired[str]
    r"""Configured product code"""
    enabled: NotRequired[bool]
    r"""Is enabled"""
    targets: NotRequired[List[str]]
    r"""Feature deployment targets"""
    options: NotRequired[
        Dict[str, GetOrganizationsDetailedSystemResponseOptionsTypedDict]
    ]
    r"""Feature options"""


class GetOrganizationsDetailedTeamviewer(BaseModel):
    r"""Feature/product/integration configuration settings"""

    product: Optional[str] = None
    r"""Configured product code"""

    enabled: Optional[bool] = None
    r"""Is enabled"""

    targets: Optional[List[str]] = None
    r"""Feature deployment targets"""

    options: Optional[Dict[str, GetOrganizationsDetailedSystemResponseOptions]] = None
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseDefaultOptionsTypedDict(TypedDict):
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseDefaultOptions(BaseModel):
    r"""Feature options"""


class GetOrganizationsDetailedBackupTypedDict(TypedDict):
    r"""Feature/product/integration configuration settings"""

    product: NotRequired[str]
    r"""Configured product code"""
    enabled: NotRequired[bool]
    r"""Is enabled"""
    targets: NotRequired[List[str]]
    r"""Feature deployment targets"""
    options: NotRequired[
        Dict[str, GetOrganizationsDetailedSystemResponseDefaultOptionsTypedDict]
    ]
    r"""Feature options"""


class GetOrganizationsDetailedBackup(BaseModel):
    r"""Feature/product/integration configuration settings"""

    product: Optional[str] = None
    r"""Configured product code"""

    enabled: Optional[bool] = None
    r"""Is enabled"""

    targets: Optional[List[str]] = None
    r"""Feature deployment targets"""

    options: Optional[
        Dict[str, GetOrganizationsDetailedSystemResponseDefaultOptions]
    ] = None
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseDefaultApplicationJSONOptionsTypedDict(
    TypedDict
):
    r"""Feature options"""


class GetOrganizationsDetailedSystemResponseDefaultApplicationJSONOptions(BaseModel):
    r"""Feature options"""


class GetOrganizationsDetailedPsaTypedDict(TypedDict):
    r"""Feature/product/integration configuration settings"""

    product: NotRequired[str]
    r"""Configured product code"""
    enabled: NotRequired[bool]
    r"""Is enabled"""
    targets: NotRequired[List[str]]
    r"""Feature deployment targets"""
    options: NotRequired[
        Dict[
            str,
            GetOrganizationsDetailedSystemResponseDefaultApplicationJSONOptionsTypedDict,
        ]
    ]
    r"""Feature options"""


class GetOrganizationsDetailedPsa(BaseModel):
    r"""Feature/product/integration configuration settings"""

    product: Optional[str] = None
    r"""Configured product code"""

    enabled: Optional[bool] = None
    r"""Is enabled"""

    targets: Optional[List[str]] = None
    r"""Feature deployment targets"""

    options: Optional[
        Dict[str, GetOrganizationsDetailedSystemResponseDefaultApplicationJSONOptions]
    ] = None
    r"""Feature options"""


class GetOrganizationsDetailedSettingsTypedDict(TypedDict):
    r"""Organization settings"""

    trayicon: NotRequired[GetOrganizationsDetailedTrayiconTypedDict]
    r"""Feature/product/integration configuration settings"""
    splashtop: NotRequired[GetOrganizationsDetailedSplashtopTypedDict]
    r"""Feature/product/integration configuration settings"""
    teamviewer: NotRequired[GetOrganizationsDetailedTeamviewerTypedDict]
    r"""Feature/product/integration configuration settings"""
    backup: NotRequired[GetOrganizationsDetailedBackupTypedDict]
    r"""Feature/product/integration configuration settings"""
    psa: NotRequired[GetOrganizationsDetailedPsaTypedDict]
    r"""Feature/product/integration configuration settings"""


class GetOrganizationsDetailedSettings(BaseModel):
    r"""Organization settings"""

    trayicon: Optional[GetOrganizationsDetailedTrayicon] = None
    r"""Feature/product/integration configuration settings"""

    splashtop: Optional[GetOrganizationsDetailedSplashtop] = None
    r"""Feature/product/integration configuration settings"""

    teamviewer: Optional[GetOrganizationsDetailedTeamviewer] = None
    r"""Feature/product/integration configuration settings"""

    backup: Optional[GetOrganizationsDetailedBackup] = None
    r"""Feature/product/integration configuration settings"""

    psa: Optional[GetOrganizationsDetailedPsa] = None
    r"""Feature/product/integration configuration settings"""


class GetOrganizationsDetailedResponseBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Organization full name"""
    description: NotRequired[str]
    r"""Organization Description"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    node_approval_mode: NotRequired[GetOrganizationsDetailedNodeApprovalMode]
    r"""Device Approval Mode"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, GetOrganizationsDetailedFieldsTypedDict]]
    r"""Custom Fields"""
    id: NotRequired[int]
    r"""Organization identifier"""
    locations: NotRequired[List[GetOrganizationsDetailedLocationsTypedDict]]
    r"""List of locations"""
    policies: NotRequired[List[GetOrganizationsDetailedPoliciesTypedDict]]
    r"""Node role policy assignments"""
    settings: NotRequired[GetOrganizationsDetailedSettingsTypedDict]
    r"""Organization settings"""


class GetOrganizationsDetailedResponseBody(BaseModel):
    name: Optional[str] = None
    r"""Organization full name"""

    description: Optional[str] = None
    r"""Organization Description"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    node_approval_mode: Annotated[
        Optional[GetOrganizationsDetailedNodeApprovalMode],
        pydantic.Field(alias="nodeApprovalMode"),
    ] = None
    r"""Device Approval Mode"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, GetOrganizationsDetailedFields]] = None
    r"""Custom Fields"""

    id: Optional[int] = None
    r"""Organization identifier"""

    locations: Optional[List[GetOrganizationsDetailedLocations]] = None
    r"""List of locations"""

    policies: Optional[List[GetOrganizationsDetailedPolicies]] = None
    r"""Node role policy assignments"""

    settings: Optional[GetOrganizationsDetailedSettings] = None
    r"""Organization settings"""
