"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ninjapy.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RestoreOrganizationChecklistsDescriptionTypedDict(TypedDict):
    r"""Task description"""

    text: NotRequired[str]
    html: NotRequired[str]


class RestoreOrganizationChecklistsDescription(BaseModel):
    r"""Task description"""

    text: Optional[str] = None

    html: Optional[str] = None


class RestoreOrganizationChecklistsAssignedToTypedDict(TypedDict):
    r"""Archive by user"""

    id: NotRequired[int]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    deleted: NotRequired[bool]


class RestoreOrganizationChecklistsAssignedTo(BaseModel):
    r"""Archive by user"""

    id: Optional[int] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    deleted: Optional[bool] = None


class RestoreOrganizationChecklistsLastUpdatedByTypedDict(TypedDict):
    r"""Archive by user"""

    id: NotRequired[int]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    deleted: NotRequired[bool]


class RestoreOrganizationChecklistsLastUpdatedBy(BaseModel):
    r"""Archive by user"""

    id: Optional[int] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    deleted: Optional[bool] = None


class RestoreOrganizationChecklistsOrganizationChecklistsDescriptionTypedDict(
    TypedDict
):
    r"""Task description"""

    text: NotRequired[str]
    html: NotRequired[str]


class RestoreOrganizationChecklistsOrganizationChecklistsDescription(BaseModel):
    r"""Task description"""

    text: Optional[str] = None

    html: Optional[str] = None


class RestoreOrganizationChecklistsOrganizationChecklistsAssignedToTypedDict(TypedDict):
    r"""Archive by user"""

    id: NotRequired[int]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    deleted: NotRequired[bool]


class RestoreOrganizationChecklistsOrganizationChecklistsAssignedTo(BaseModel):
    r"""Archive by user"""

    id: Optional[int] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    deleted: Optional[bool] = None


class RestoreOrganizationChecklistsCompletedByTypedDict(TypedDict):
    r"""Archive by user"""

    id: NotRequired[int]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    deleted: NotRequired[bool]


class RestoreOrganizationChecklistsCompletedBy(BaseModel):
    r"""Archive by user"""

    id: Optional[int] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    deleted: Optional[bool] = None


class RestoreOrganizationChecklistsTasksTypedDict(TypedDict):
    r"""Checklist's tasks"""

    id: NotRequired[int]
    r"""Identifier"""
    position: NotRequired[int]
    r"""Position of the task"""
    name: NotRequired[str]
    r"""Task name"""
    description: NotRequired[
        RestoreOrganizationChecklistsOrganizationChecklistsDescriptionTypedDict
    ]
    r"""Task description"""
    assigned_to: NotRequired[
        RestoreOrganizationChecklistsOrganizationChecklistsAssignedToTypedDict
    ]
    r"""Archive by user"""
    due_date: NotRequired[float]
    r"""Due date"""
    completed: NotRequired[bool]
    r"""Indicates if the checklist is completed"""
    completed_on: NotRequired[float]
    r"""Date of completion"""
    completed_by: NotRequired[RestoreOrganizationChecklistsCompletedByTypedDict]
    r"""Archive by user"""


class RestoreOrganizationChecklistsTasks(BaseModel):
    r"""Checklist's tasks"""

    id: Optional[int] = None
    r"""Identifier"""

    position: Optional[int] = None
    r"""Position of the task"""

    name: Optional[str] = None
    r"""Task name"""

    description: Optional[
        RestoreOrganizationChecklistsOrganizationChecklistsDescription
    ] = None
    r"""Task description"""

    assigned_to: Annotated[
        Optional[RestoreOrganizationChecklistsOrganizationChecklistsAssignedTo],
        pydantic.Field(alias="assignedTo"),
    ] = None
    r"""Archive by user"""

    due_date: Annotated[Optional[float], pydantic.Field(alias="dueDate")] = None
    r"""Due date"""

    completed: Optional[bool] = None
    r"""Indicates if the checklist is completed"""

    completed_on: Annotated[Optional[float], pydantic.Field(alias="completedOn")] = None
    r"""Date of completion"""

    completed_by: Annotated[
        Optional[RestoreOrganizationChecklistsCompletedBy],
        pydantic.Field(alias="completedBy"),
    ] = None
    r"""Archive by user"""


class RestoreOrganizationChecklistsArchivedByTypedDict(TypedDict):
    r"""Archive by user"""

    id: NotRequired[int]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    deleted: NotRequired[bool]


class RestoreOrganizationChecklistsArchivedBy(BaseModel):
    r"""Archive by user"""

    id: Optional[int] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    deleted: Optional[bool] = None


class RestoreOrganizationChecklistsResponseBodyTypedDict(TypedDict):
    id: NotRequired[int]
    r"""Identifier"""
    name: NotRequired[str]
    r"""Checklist name (must be unique)"""
    description: NotRequired[RestoreOrganizationChecklistsDescriptionTypedDict]
    r"""Task description"""
    required: NotRequired[bool]
    r"""Indicates if the checklist completion is required"""
    due_date: NotRequired[float]
    r"""Due date"""
    completed: NotRequired[bool]
    r"""Indicates if the checklist is completed"""
    completed_on: NotRequired[float]
    r"""Date of completion"""
    assigned_to: NotRequired[RestoreOrganizationChecklistsAssignedToTypedDict]
    r"""Archive by user"""
    last_updated_on: NotRequired[float]
    r"""Last updated on"""
    last_updated_by: NotRequired[RestoreOrganizationChecklistsLastUpdatedByTypedDict]
    r"""Archive by user"""
    completed_task_count: NotRequired[int]
    r"""Last updated by user"""
    total_task_count: NotRequired[int]
    r"""Checklist's total tasks count"""
    tasks: NotRequired[List[RestoreOrganizationChecklistsTasksTypedDict]]
    r"""Checklist's tasks"""
    organization_id: NotRequired[int]
    r"""Organization identifier"""
    client_name: NotRequired[str]
    r"""Client name"""
    archived: NotRequired[bool]
    r"""Indicates if the checklist is archived"""
    archived_by: NotRequired[RestoreOrganizationChecklistsArchivedByTypedDict]
    r"""Archive by user"""
    archive_time: NotRequired[float]
    r"""Archive time"""


class RestoreOrganizationChecklistsResponseBody(BaseModel):
    id: Optional[int] = None
    r"""Identifier"""

    name: Optional[str] = None
    r"""Checklist name (must be unique)"""

    description: Optional[RestoreOrganizationChecklistsDescription] = None
    r"""Task description"""

    required: Optional[bool] = None
    r"""Indicates if the checklist completion is required"""

    due_date: Annotated[Optional[float], pydantic.Field(alias="dueDate")] = None
    r"""Due date"""

    completed: Optional[bool] = None
    r"""Indicates if the checklist is completed"""

    completed_on: Annotated[Optional[float], pydantic.Field(alias="completedOn")] = None
    r"""Date of completion"""

    assigned_to: Annotated[
        Optional[RestoreOrganizationChecklistsAssignedTo],
        pydantic.Field(alias="assignedTo"),
    ] = None
    r"""Archive by user"""

    last_updated_on: Annotated[
        Optional[float], pydantic.Field(alias="lastUpdatedOn")
    ] = None
    r"""Last updated on"""

    last_updated_by: Annotated[
        Optional[RestoreOrganizationChecklistsLastUpdatedBy],
        pydantic.Field(alias="lastUpdatedBy"),
    ] = None
    r"""Archive by user"""

    completed_task_count: Annotated[
        Optional[int], pydantic.Field(alias="completedTaskCount")
    ] = None
    r"""Last updated by user"""

    total_task_count: Annotated[
        Optional[int], pydantic.Field(alias="totalTaskCount")
    ] = None
    r"""Checklist's total tasks count"""

    tasks: Optional[List[RestoreOrganizationChecklistsTasks]] = None
    r"""Checklist's tasks"""

    organization_id: Annotated[
        Optional[int], pydantic.Field(alias="organizationId")
    ] = None
    r"""Organization identifier"""

    client_name: Annotated[Optional[str], pydantic.Field(alias="clientName")] = None
    r"""Client name"""

    archived: Optional[bool] = None
    r"""Indicates if the checklist is archived"""

    archived_by: Annotated[
        Optional[RestoreOrganizationChecklistsArchivedBy],
        pydantic.Field(alias="archivedBy"),
    ] = None
    r"""Archive by user"""

    archive_time: Annotated[Optional[float], pydantic.Field(alias="archiveTime")] = None
    r"""Archive time"""
