"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from ninjapy.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RestoreMultiPageClientDocumentsValueTypedDict(TypedDict):
    r"""Value"""


class RestoreMultiPageClientDocumentsValue(BaseModel):
    r"""Value"""


class RestoreMultiPageClientDocumentsFieldsTypedDict(TypedDict):
    r"""Updated Fields"""

    name: NotRequired[str]
    r"""Name"""
    value: NotRequired[RestoreMultiPageClientDocumentsValueTypedDict]
    r"""Value"""
    value_update_time: NotRequired[float]
    r"""Value Last Updated"""


class RestoreMultiPageClientDocumentsFields(BaseModel):
    r"""Updated Fields"""

    name: Optional[str] = None
    r"""Name"""

    value: Optional[RestoreMultiPageClientDocumentsValue] = None
    r"""Value"""

    value_update_time: Optional[float] = None
    r"""Value Last Updated"""


class RestoreMultiPageClientDocumentsResponseBodyTypedDict(TypedDict):
    document_id: NotRequired[int]
    r"""Document Identifier"""
    document_name: NotRequired[str]
    r"""Document Name"""
    document_description: NotRequired[str]
    r"""Document Description"""
    document_update_time: NotRequired[float]
    r"""Document Last Updated"""
    fields: NotRequired[List[RestoreMultiPageClientDocumentsFieldsTypedDict]]
    r"""Fields"""
    document_template_id: NotRequired[int]
    r"""Document Template Identifier"""
    document_template_name: NotRequired[str]
    r"""Document Template Name"""
    organization_id: NotRequired[int]
    r"""Organization Identifier"""


class RestoreMultiPageClientDocumentsResponseBody(BaseModel):
    document_id: Optional[int] = None
    r"""Document Identifier"""

    document_name: Optional[str] = None
    r"""Document Name"""

    document_description: Optional[str] = None
    r"""Document Description"""

    document_update_time: Optional[float] = None
    r"""Document Last Updated"""

    fields: Optional[List[RestoreMultiPageClientDocumentsFields]] = None
    r"""Fields"""

    document_template_id: Optional[int] = None
    r"""Document Template Identifier"""

    document_template_name: Optional[str] = None
    r"""Document Template Name"""

    organization_id: Optional[int] = None
    r"""Organization Identifier"""
