"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from ninjapy.types import BaseModel
from ninjapy.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateOrganizationNodeApprovalMode(str, Enum):
    r"""Device Approval Mode"""

    AUTOMATIC = "AUTOMATIC"
    MANUAL = "MANUAL"
    REJECT = "REJECT"


class UpdateOrganizationFieldsTypedDict(TypedDict):
    r"""Custom Fields"""


class UpdateOrganizationFields(BaseModel):
    r"""Custom Fields"""


class UpdateOrganizationRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Organization full name"""
    description: NotRequired[str]
    r"""Organization Description"""
    user_data: NotRequired[Dict[str, Any]]
    r"""Custom attributes"""
    node_approval_mode: NotRequired[UpdateOrganizationNodeApprovalMode]
    r"""Device Approval Mode"""
    tags: NotRequired[List[str]]
    r"""Tags"""
    fields: NotRequired[Dict[str, UpdateOrganizationFieldsTypedDict]]
    r"""Custom Fields"""


class UpdateOrganizationRequestBody(BaseModel):
    name: Optional[str] = None
    r"""Organization full name"""

    description: Optional[str] = None
    r"""Organization Description"""

    user_data: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="userData")] = (
        None
    )
    r"""Custom attributes"""

    node_approval_mode: Annotated[
        Optional[UpdateOrganizationNodeApprovalMode],
        pydantic.Field(alias="nodeApprovalMode"),
    ] = None
    r"""Device Approval Mode"""

    tags: Optional[List[str]] = None
    r"""Tags"""

    fields: Optional[Dict[str, UpdateOrganizationFields]] = None
    r"""Custom Fields"""


class UpdateOrganizationRequestTypedDict(TypedDict):
    id: int
    r"""Organization identifier"""
    request_body: NotRequired[UpdateOrganizationRequestBodyTypedDict]


class UpdateOrganizationRequest(BaseModel):
    id: Annotated[
        int, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Organization identifier"""

    request_body: Annotated[
        Optional[UpdateOrganizationRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
