workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    NinjaOne Public API 2.0:
        inputs:
            - location: https://app.ninjarmm.com/apidocs/NinjaRMM-API-v2.json
        registry:
            location: registry.speakeasyapi.dev/imagenet/managedit/ninja-one-public-api-2-0
targets:
    ninjapy:
        target: python
        source: NinjaOne Public API 2.0
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/imagenet/managedit/ninja-one-public-api-2-0-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
